### PR TITLE
Move from my personal repo to 47deg

### PR DESCRIPTION
**Pull request by andyscott**

### CODE REVIEW

**Comment by andyscott** [comment]
@raulraja @fedefernandez I haven't updated the COPYING file-- some of the code in this repo is from Scala and/or Paul Phillips. Any idea how we should adjust the licensing?

**Comment by raulraja** [comment]
Mention appropriate licenses for all sources and it should be fine.

**Comment by raulraja** [comment]
Same with copyrights

**Comment by andyscott** [comment]
I think it should be good. Take a look, and you can have the merge honors.

**Comment by raulraja** [comment]
LGTM!

**Pull request merged**
